### ISSUE TITLE
Demos for segmentation and object detection are not working.

### ISSUE THREAD

**Issue by nitikaaggarwal** [EliotAndres/pretrained.ml#3]
![screen shot 2018-08-09 at 1 40 37 am](https://user-images.githubusercontent.com/2610878/43888718-2fc88e9a-9b77-11e8-838e-97ac0ce91649.png)

**Comment by EliotAndres** [comment]
Hi ! Thank you for pointing it out. It should be fixed.
Please note that this website will stop working at the end of the month
Eliot
